n$40=_fun___new(sizeof():) [line 1]
*&Bundle:=n$40 [line 2]
n$41=*&Bundle: [line 3]
n$42=_fun___new(sizeof():) [line 4]
_fun_AttributeSettersActivity.<init>()(n$42:) [line 5]
*&AttributeSettersActivity:=n$42 [line 6]
n$43=*&AttributeSettersActivity: [line 7]
_fun_void AttributeSettersActivity.onCreate(Bundle)(n$43:,n$41:) virtual [line 8]
