n$61=_fun___new(sizeof():) [line 1]
*&Bundle:=n$61 [line 2]
n$62=*&Bundle: [line 3]
n$63=_fun___new(sizeof():) [line 4]
_fun_CustomBindingActivity.<init>()(n$63:) [line 5]
*&CustomBindingActivity:=n$63 [line 6]
n$64=*&CustomBindingActivity: [line 7]
_fun_void CustomBindingActivity.onCreate(Bundle)(n$64:,n$62:) virtual [line 8]
