n$57=_fun___new(sizeof():) [line 1]
*&Bundle:=n$57 [line 2]
n$58=*&Bundle: [line 3]
n$59=_fun___new(sizeof():) [line 4]
_fun_ViewWithIDsActivity.<init>()(n$59:) [line 5]
*&ViewWithIDsActivity:=n$59 [line 6]
n$60=*&ViewWithIDsActivity: [line 7]
_fun_void ViewWithIDsActivity.onCreate(Bundle)(n$60:,n$58:) virtual [line 8]
