n$28=_fun___new(sizeof():) [line 1]
*&Bundle:=n$28 [line 2]
n$29=*&Bundle: [line 3]
n$30=_fun___new(sizeof():) [line 4]
_fun_ConversionsActivity.<init>()(n$30:) [line 5]
*&ConversionsActivity:=n$30 [line 6]
n$31=*&ConversionsActivity: [line 7]
_fun_void ConversionsActivity.onCreate(Bundle)(n$31:,n$29:) virtual [line 8]
