n$44=_fun___new(sizeof():) [line 1]
*&Bundle:=n$44 [line 2]
n$45=*&Bundle: [line 3]
n$46=_fun___new(sizeof():) [line 4]
_fun_ViewStubActivity.<init>()(n$46:) [line 5]
*&ViewStubActivity:=n$46 [line 6]
n$47=*&ViewStubActivity: [line 7]
_fun_void ViewStubActivity.onCreate(Bundle)(n$47:,n$45:) virtual [line 8]
n$48=*&#GB$com.liangfeizc.databinding.sample.viewstub.ViewStubActivity.InferGeneratedHarness().android.view.ViewStub$OnInflateListener[line 22]: [line 9]
n$49=_fun___new(sizeof():) [line 10]
*&View:=n$49 [line 11]
n$50=*&View: [line 12]
n$51=_fun___new(sizeof():) [line 13]
*&ViewStub:=n$51 [line 14]
n$52=*&ViewStub: [line 15]
_fun_void ViewStubActivity$1.onInflate(ViewStub,View)(n$48:,n$52:,n$50:) virtual [line 16]
